### PR TITLE
13 fix mapping error

### LINKED ISSUE #13: Fix infinite recursion on mapping
On mapping the DAO to the DTO Mapstruct encounters some sort of infinite recursion resulting in an Stack Overflow Error. Ignoring Mapping targets should be sufficient.

### PR DESCRIPTION
**Pull request by alexmsenger**
Closes #13

### CODE REVIEW

File: src/main/java/de/yfu/intranet/seminars/api/resources/mapper/GoalMapper.java [hunk 1]
```diff
@@ -18,18 +19,23 @@
 public interface GoalMapper {
 
     Goal mapToGoal(GoalResource goalResource);
+//    @Mapping( target = "type", ignore = true)
```
Comment (alexmsenger) [inline src/main/java/de/yfu/intranet/seminars/api/resources/mapper/GoalMapper.java]: remove comment
